apiVersion: v1
kind: Service
metadata:
  name: shopeasy-service
spec:
  type: NodePort
  selector:
    app: shopeasy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001 # You will access the site at http://localhost:30001
